from enum import Enum


class OperationStatus(str, Enum):
    SUCCESS = "SUCCESS"
    PARTIAL = "PARTIAL"
    FAILURE = "FAILURE"


class DataState(str, Enum):
    READY = "READY"
    PENDING = "PENDING"
    STALE = "STALE"
    EMPTY = "EMPTY"
    UNAVAILABLE = "UNAVAILABLE"


class MarketGovernanceState(str, Enum):
    DRAFT = "DRAFT"
    IN_REVIEW = "IN_REVIEW"
    APPROVED = "APPROVED"
    PUBLISHED = "PUBLISHED"
    SUPERSEDED = "SUPERSEDED"
    RETRACTED = "RETRACTED"


class CapabilityAvailability(str, Enum):
    AVAILABLE = "AVAILABLE"
    DEGRADED = "DEGRADED"
    NOT_READY = "NOT_READY"
    UNAVAILABLE = "UNAVAILABLE"


class ReleaseIdentityEvidenceBasis(str, Enum):
    PROVIDER_ATTESTED = "PROVIDER_ATTESTED"
    MANIFEST_VERIFIED = "MANIFEST_VERIFIED"
    ARTIFACT_IDENTITY_VERIFIED = "ARTIFACT_IDENTITY_VERIFIED"
    ARTIFACT_DIGEST_VERIFIED = "ARTIFACT_DIGEST_VERIFIED"
    SOURCE_BUILD_LINEAGE_VERIFIED = "SOURCE_BUILD_LINEAGE_VERIFIED"
    UNKNOWN = "UNKNOWN"


class ProvenanceStatus(str, Enum):
    PROVENANCE_COMPLETE = "PROVENANCE_COMPLETE"
    PROVENANCE_INCOMPLETE = "PROVENANCE_INCOMPLETE"


class OperationKind(str, Enum):
    READ = "READ"
    ANALYTICAL_INTERROGATION = "ANALYTICAL_INTERROGATION"
    DATA_REFRESH = "DATA_REFRESH"
    COMPOSITE = "COMPOSITE"


class SideEffectClass(str, Enum):
    READ_ONLY = "READ_ONLY"
    DATA_REFRESH = "DATA_REFRESH"
    MARKET_STATE_MUTATION = "MARKET_STATE_MUTATION"
    PRODUCT_CREATION = "PRODUCT_CREATION"
    GOVERNED_AUTHORITY_CHANGE = "GOVERNED_AUTHORITY_CHANGE"
    COMPOSITE = "COMPOSITE"
