from enum import Enum


class OperationStatus(str, Enum):
    SUCCESS = "SUCCESS"
    PARTIAL = "PARTIAL"
    FAILURE = "FAILURE"


class DataState(str, Enum):
    READY = "READY"
    PENDING = "PENDING"
    STALE = "STALE"
    EMPTY = "EMPTY"
    UNAVAILABLE = "UNAVAILABLE"


class MarketGovernanceState(str, Enum):
    DRAFT = "DRAFT"
    IN_REVIEW = "IN_REVIEW"
    APPROVED = "APPROVED"
    PUBLISHED = "PUBLISHED"
    SUPERSEDED = "SUPERSEDED"
    RETRACTED = "RETRACTED"


class CapabilityAvailability(str, Enum):
    AVAILABLE = "AVAILABLE"
    DEGRADED = "DEGRADED"
    NOT_READY = "NOT_READY"
    UNAVAILABLE = "UNAVAILABLE"


class ReleaseIdentityEvidenceBasis(str, Enum):
    PROVIDER_ATTESTED = "PROVIDER_ATTESTED"
    MANIFEST_VERIFIED = "MANIFEST_VERIFIED"
    ARTIFACT_IDENTITY_VERIFIED = "ARTIFACT_IDENTITY_VERIFIED"
    ARTIFACT_DIGEST_VERIFIED = "ARTIFACT_DIGEST_VERIFIED"
    SOURCE_BUILD_LINEAGE_VERIFIED = "SOURCE_BUILD_LINEAGE_VERIFIED"
    UNKNOWN = "UNKNOWN"


class ProvenanceStatus(str, Enum):
    PROVENANCE_COMPLETE = "PROVENANCE_COMPLETE"
    PROVENANCE_INCOMPLETE = "PROVENANCE_INCOMPLETE"


class ReadinessState(str, Enum):
    READY = "READY"
    DEGRADED = "DEGRADED"
    NOT_READY = "NOT_READY"
    UNAVAILABLE = "UNAVAILABLE"


class CompatibilityState(str, Enum):
    COMPATIBLE = "COMPATIBLE"
    CONTRACT_MISMATCH = "CONTRACT_MISMATCH"
    RELEASE_MISMATCH = "RELEASE_MISMATCH"
    UNKNOWN = "UNKNOWN"


class OperationKind(str, Enum):
    READ = "READ"
    ANALYTICAL_INTERROGATION = "ANALYTICAL_INTERROGATION"
    DATA_REFRESH = "DATA_REFRESH"
    COMPOSITE = "COMPOSITE"


class SideEffectClass(str, Enum):
    READ_ONLY = "READ_ONLY"
    REVERSIBLE_WRITE = "REVERSIBLE_WRITE"
    IRREVERSIBLE_WRITE = "IRREVERSIBLE_WRITE"
    EXTERNAL_SIDE_EFFECT = "EXTERNAL_SIDE_EFFECT"
    HIGH_IMPACT = "HIGH_IMPACT"
